fix: permissons
Without this permission the error showed instead of release:
Error: Resource not accessible by integration

And enable in Repository Configurations -> Actions -> General -> [Read and write permission]